### ISSUE TITLE
Failed to activate the linter-clojure package

### ISSUE THREAD

**Issue by masarum** [AtomLinter/linter-clojure#12]
[Enter steps to reproduce below:]

1. Set configs
2. Restart

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-clojure](https://github.com/AtomLinter/linter-clojure) package, v1.1.0

### Stack Trace

Failed to activate the linter-clojure package

```
At require(...)(...)[1].getFileName is not a function

TypeError: require(...)(...)[1].getFileName is not a function
    at Object.install (/Users/masaru/.atom/packages/linter-clojure/node_modules/atom-package-deps/lib/main.js:15:47)
    at Object.module.exports.activate (/Users/masaru/.atom/packages/linter-clojure/lib/init.coffee:11:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:490:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:671:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:38:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:49:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:79:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "proto-repl"
    ],
    "audioBeep": false,
    "ignoredNames": [
      ".meteor"
    ],
    "themes": [
      "isotope-ui",
      "zenburn-syntax"
    ]
  },
  "linter-clojure": {
    "clojureExecutablePath": "/Users/masaru/.m2/repository/org/clojure/clojure/1.7.0/clojure-1.7.0.jar",
    "javaExecutablePath": "/usr/bin/java"
  }
}
```

### Installed Packages

```coffee
# User
Parinfer, v0.8.1
Stylus, v1.2.1
atom-html-preview, v0.1.13
auto-indent, v0.5.0
autocomplete-paths, v1.0.2
coffee-compile, v0.20.0
color-picker, v2.0.13
emmet, v2.3.14
file-icons, v1.6.11
haskell-ghc-mod, v1.1.5
isotope-ui, v2.7.0
language-babel, v2.5.0
language-fish-shell, v1.0.2
language-haskell, v1.5.1
language-jade, v0.6.2
language-scala, v1.1.4
language-spacebars, v0.2.2
linter, v1.11.2
linter-clojure, v1.1.0
linter-eslint, v5.2.1
minimap, v4.16.1
regex-railroad-diagram, v0.10.4
select-rectangle, v1.0.2
source-preview-babel, v0.1.1
space-tab, v0.4.2
sync-settings, v0.6.0
zenburn-syntax, v0.0.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/package-deps/pull/31

Here's what you can do to make it work on your installation
```
cd ~/.atom/packages/linter-php
rm -rf node_modules/atom-package-deps
npm install atom-package-deps@latest
```

I'll publish a release with the latest version in the meanwhile

**Comment by masarum** [comment]
Fix confirmed, thanks!
