### ISSUE TITLE
Unable to resolve symbol: defproject in this context

### ISSUE THREAD

**Issue by jefffriesen** [AtomLinter/linter-clojure#54]
Setting up a brand new repo:
```
lein new myproject
```

I get this error on project.clj
> Unable to resolve symbol: defproject in this context

I'm using Clojure 1.8.0. Any suggestions?

**Comment by Arcanemagus** [comment]
Does `java -jar path/to/clojure.jar -i project.clj` show the same message?

**Comment by roneygomes** [comment]
Hi.

I'm also having the same problem. Evaluating `project.clj` with Clojure's jar gives me the following the stack trace:

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: defproject in this context, compiling:(/Users/rngomes/code/projects/personal/clojure/coding-game/project.clj:1:1)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3766)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler.eval(Compiler.java:6931)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: defproject in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7164)
	at clojure.lang.Compiler.resolve(Compiler.java:7108)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7069)
	at clojure.lang.Compiler.analyze(Compiler.java:6648)
	... 21 more
```
From what I could get by googling about this, it seems we're not really supposed to evaluate `project.clj`. Perhaps there should be some special way of dealing with this file, or just ignore it altogether? I'm new to closure so am not really sure.

**Comment by juhnowski** [comment]
+1

**Comment by WildSaoFeng** [comment]
+2

**Comment by hurkgu** [comment]
+3

**Comment by HarneetK123** [comment]
+5

**Comment by niminuko** [comment]
+6

**Comment by croesusking** [comment]
lmao no one is answering oml

**Comment by SylvianHemus** [comment]
+6
think you're supposed to go to core/core.clj lawl
