### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by justCxx** [AtomLinter/linter-clojure#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Ubuntu 15.04
**Thrown From**: [linter-clojure](https://github.com/AtomLinter/linter-clojure) package, v1.0.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
  at /home/justcxx/.atom/packages/linter-clojure/node_modules/atom-linter/lib/helpers.coffee:45:30
  at Object.module.exports.Helpers._exec (/home/justcxx/.atom/packages/linter-clojure/node_modules/atom-linter/lib/helpers.coffee:25:16)
  at Object.module.exports.Helpers.exec (/home/justcxx/.atom/packages/linter-clojure/node_modules/atom-linter/lib/helpers.coffee:16:13)
  at Object.provider.lint (/home/justcxx/.atom/packages/linter-clojure/lib/init.coffee:27:24)
  at Promise.then._this.emitter.emit.linter (/home/justcxx/.atom/packages/linter/lib/linter-registry.coffee:59:22)
  at LinterRegistry.triggerLinter (/home/justcxx/.atom/packages/linter/lib/linter-registry.coffee:58:16)
  at /home/justcxx/.atom/packages/linter/lib/linter-registry.coffee:52:17
  at Array.map (native)
  at /home/justcxx/.atom/packages/linter/lib/linter-registry.coffee:50:27

```

### Commands

```
     -0:03.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 linter:lint (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "bookmarks",
      "language-csharp",
      "language-perl",
      "language-objective-c",
      "welcome",
      "linter-xmllint",
      "linter-cpplint",
      "color-picker",
      "git-blame",
      "git-log",
      "linter-php",
      "linter-pylint",
      "linter-jscs",
      "linter-clang",
      "linter-ruby"
    ]
  },
  "linter-clojure": {
    "clojureExecutablePath": "/home/justcxx/.m2/repository/org/clojure/clojure/1.7.0/clojure-1.7.0.jar",
    "javaExecutablePath": "/usr/bin"
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
file-icons, v1.6.9
git-diff-details, v0.20.0
language-scheme, v1.4.0
linter, v1.5.0
linter-clojure, v1.0.0
linter-erb, v0.1.1
linter-eslint, v3.0.2
linter-js-yaml, v1.1.1
linter-rubocop, v0.3.4
regex-railroad-diagram, v0.8.4
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
svg-preview, v0.6.1
tree-view-git-status, v0.2.0
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Your exec file isn't marked as executable, You should do `chmod +x /home/justcxx/.m2/repository/org/clojure/clojure/1.7.0/clojure-1.7.0.jar` and try again

**Comment by justCxx** [comment]
Thanks!
